### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by zentavr** [Luzilla/dnsbl_exporter#168]
Hello @till.

I'd developed a helm chart which installs dnsbl-exporter into Kubernetes clusters. Just a simple Daemonset, configmap (no Ingress). If you are interested, I can submit a PR of that.

P.S.: Unfortunately I cannot fetch the docker image from:
```
image:
  registry: ghcr.io
  repository: luzilla/dnsbl_exporter
  tag: v0.6.0
```
...so I'd build my own container using the binaries from the Release page of that repo.
