### ISSUE TITLE
helm repo needs authentication

### ISSUE THREAD

**Issue by vquie** [Luzilla/dnsbl_exporter#213]
Installing the helm chart does not work. The repo requires auth.

Please allow unauthenticated access to the repo.

```
STDERR:
  Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aluzilla%2Fcharts%2Fdnsbl-exporter%2Fdnsbl-exporter%3Apull&service=ghcr.io: 403 Forbidden
```

**Comment by till** [comment]
@vquie I'll take a look, I thought I tested this. Artifact Hub was also unable to pull.

**Comment by till** [comment]
Can you test this here:

https://github.com/Luzilla/dnsbl_exporter/pkgs/container/charts%2Fdnsbl-exporter/198236263?tag=0.1.0

Helm should use the same mechanism.

**Comment by till** [comment]
@vquie It looks like your error message contains the chart name twice. Did I typo the instructions somewhere?

**Comment by vquie** [comment]
Thanks. It works now and it was my bad I guess.

I added it to helmfile

not working
```yaml
repositories:
  - name: dnsbl-exporter
    url: ghcr.io/luzilla/charts/dnsbl-exporter
    oci: true
```

working
```yaml
repositories:
  - name: dnsbl-exporter
    url: ghcr.io/luzilla/charts
    oci: true
```
