### ISSUE TITLE
Support modules configuration

### ISSUE THREAD

**Issue by dragoangel** [Luzilla/dnsbl_exporter#225]
I think such exporter would be fit much better with `/probe?module=rbl_ips&target=192.0.2.1` or `/probe?module=rbl_domains&target=example.com`, like it done in blackbox exporter, ssl exporter, etc. It will allow people who using stuff like Prometheus Operator control which things to monitor by simply proving CRDs in k8s to probe, instead of creating\adjusting configuration of exporter, this is much more dynamic flow. People without Prometheus Operator still can just edit prometheys.yaml without accessing and redeploying dnsbl exporter.

In this way `dnsbl_exporter.conf` configuration of module would have next scheme:
```yaml
modules:
  <module_name_used_by_probe>: # meaning name of rbls to check with
    prober: dnsbl # name of modules that supported by exporter, if there no differnce between rbl resolving that should be treaded specially - this will be always dnsbl
    timeout: <duration> # module timeout
    dnsbl: # if not changed in prober, configures module behaviour
      # qeuery ips by default, f.e IPv4 192.0.2.1 would query 0.2.0.192.rbl-example.com
      # and IPv6 2001:db8:: - 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.rbl-example.com
      # if set to false query will be done as-is, f.e:
      # if target is mysite.com - then query is mysite.com.rbl-example.com.
      ips: true
      hashing: nil # defaults to no hashing, options: md5, sha1, sha256, etc.
      rbls:
        - <rbl.example.com>
        - <rbl2.example.com>
      resolvers: # if unset system resolvers will be used
        - <ns1.example.com>
        - <ns2.example.com>
```

resulting in:
```yaml
modules:
  rbls_ips:
    prober: dnsbl
    timeout: 3s
    dnsbl:
      rbl_servers:
        - ix.dnsbl.manitu.net
        - zen.spamhaus.org
      resolvers:
        - 192.0.2.10
  rbl_domains:
    prober: dnsbl
    timeout: 3s
    dnsbl:
      ips: false
      rbl_servers:
        - dbl.spamhaus.org
```
Such workflow also as you see would allow using custom dns resolver per each module.

Here how would Prometheus probes would look like with probes flow:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
spec:
  interval: 15m
  jobName: myips
  module: rbl_ips
  prober:
    path: /probe
    scheme: http
    url: dnsbl-exporter.svc:9211
  scrapeTimeout: 5s
  targets:
    staticConfig:
      static:
        - 192.0.2.1
        - 192.0.2.2
        - 192.0.2.3
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
spec:
  interval: 15m
  jobName: mydomains
  module: rbl_domains
  prober:
    path: /probe
    scheme: http
    url: dnsbl-exporter.svc:9211
  scrapeTimeout: 5s
  targets:
    staticConfig:
      static:
        - example.com
        - example.org
```

**Comment by till** [comment]
Hey, there's already a probe endpoint, but I think it currently does not support domain based lookups.

**Comment by till** [comment]
I was wrong! :D When you start the exporter with `--domain.based`, then a request to `/prober?target=x.y.z` uses the domain based lookup. :) 

Code is here:
https://github.com/Luzilla/dnsbl_exporter/blob/main/internal/prober/prober.go

What changes would you suggest?

**Comment by dragoangel** [comment]
> Hey, there's already a probe endpoint, but I think it currently does not support domain based lookups.

Well I checked usage README.md and do not see anything which would mention such option.

**Comment by till** [comment]
> > Hey, there's already a probe endpoint, but I think it currently does not support domain based lookups.
> 
> Well I checked usage README.md and do not see anything which would mention such option or describe it's configuration flow.

No worries. I know not everything might be documented adequately. So assuming the exporter does what you need already, I would really like a PR adjusting the README or adding the required information to it. :)

**Comment by dragoangel** [comment]
> > > Hey, there's already a probe endpoint, but I think it currently does not support domain based lookups.
> > 
> > 
> > Well I checked usage README.md and do not see anything which would mention such option or describe it's configuration flow.
> 
> No worries. I know not everything might be documented adequately. So assuming the exporter does what you need already, I would really like a PR adjusting the README or adding the required information to it. :)

Then usage `modules` part with configuration options would eliminate need of setting any extra argument flags and will not lock users to just one DNS server, as each module would have option to use own set of RBL and NS and in future if needed - more options.

**Comment by till** [comment]
@dragoangel I am open to supporting your use cases. Do you want to start a PR?

The question of "multiple" resolvers comes up again and again. Still not entirely sure how to to implement that. I defer it to a local unbound.

For the hashing bit - I am not familiar with that. Do you have an example?

**Comment by dragoangel** [comment]
Hashing is rare thing, used to encode in rbl exactly links, like phishtank or emails, don't think someone would activelly used it 😅 in exporter, it was more to provide ideology on configuration I mean - that it allows to properly expand functionality without hardcoding thins.

**Comment by dragoangel** [comment]
About multiply resolvers and PR, unfortunately can't say my Go skills (none) and free time would allow to create PRs 😓, but maybe this as options could help:

- https://stackoverflow.com/questions/59889882/specifying-dns-server-for-lookup-in-go
- https://github.com/Focinfi/go-dns-resolver

**Comment by dragoangel** [comment]
I renamed issue, to not confuse anybody :)

**Comment by dragoangel** [comment]
About documentation - I will deploy it and after checking how ut goes will create PR with my findings

**Comment by dragoangel** [comment]
I'm also can provide PR to helm to support modules things if they would be in place 😊

**Comment by dragoangel** [comment]
@till `/prober` is not default thing to use, by default it should be `/probe`, and another thing: usually when exporter working with probes, default `/metrics` returns general details about exporter, which in case of dnsbl could be dns resolving time, resolving failures, total or gauge etc.

**Comment by dragoangel** [comment]
Another thing that could be cool:
```yaml
rbl_responses:
  <rbl_domain_name>:
    ignored_responses:
      - 127.0.0.7
    ignored_response_ranges:
      - 127.0.0.100-127.0.0.115
    blocked_responses:
      - 127.0.0.1
    ignored_response_ranges:
      - 127.0.0.120-127.0.0.135
    rate_limited_responses:
      - 127.0.0.8
    rate_limited_response_ranges:
      - 127.0.0.200-127.0.0.215
```

This would allow to exclude false positive of `luzilla_rbls_ips_blacklisted`
