### ISSUE TITLE
SpamHaus "blocked" answers

### ISSUE THREAD

**Issue by lapo-luchini** [Luzilla/dnsbl_exporter#264]
SpamHaus recently started responding in the `127.255.255.0/24` net for [blocked queries](https://www.spamhaus.org/resource-hub/dnsbl/using-our-public-mirrors-check-your-return-codes-now/#127.255.255.252-or-typing-error-in-dnsbl-name) (also, it's saying my DNS is a public one and I'm using a local resolver, so I guess their checks are flaky) so it would be better to ignore that kind of values as "no answer" instead of "it is spam" to avoid false positives.

I have a lot fo false positives from abuseat/spamhaus domains since `2025-05-13 17:51:00`.

**Comment by till** [comment]
Can you comment how you setup your local resolver? The helm chart contains an unbound sidecar as an example which seems to work. How's your setup different?

**Comment by lapo-luchini** [comment]
Unfortunately it's not happening anymore.
As soon as it happens again I will take care of saving some response and/or try a PR myself, thanks!

**Comment by lapo-luchini** [comment]
I managed to reproduce the problem using an "actual" DNS problem (the DNS of my provider):
```
% drill a 99.2.9.176.sbl.spamhaus.org @185.12.64.1
;; ANSWER SECTION:
99.2.9.176.sbl.spamhaus.org.    2100    IN      A       127.255.255.254
% drill txt 99.2.9.176.sbl.spamhaus.org @185.12.64.1
;; ANSWER SECTION:
99.2.9.176.sbl.spamhaus.org.    2100    IN      TXT     "Error: open resolver; https://check.spamhaus.org/returnc/pub/2a01:4f8:0:a231::add:2d/"
```
I also saved a tcpdump of the packets, if it could be useful, I'm willing to send it my email (I'm not sure I want to attach the file here publicly).

**Comment by dragoangel** [comment]
This what I was speaking about different responses for different rbls handling in https://github.com/Luzilla/dnsbl_exporter/issues/225#issuecomment-2120955261 - maybe we better rename this FR and think not about spamhaus but about general cases when users want to have special handling for different answers?

**Comment by dragoangel** [comment]
we can hardcode that `blacklisted` is used for firing `luzilla_rbls_ips_blacklisted` but every other reply from `range` just exported as extra label. One thing to check on startup - that for 1 `<rbl_domain_name>` we do not have overlapping responses\ranges between different responses and fail if this happen due to misconfiguration. Example of missconfiguration:
```yaml
rbl_configuration:
  <rbl_domain_name>:
    blacklisted:
      - response: 127.0.0.2
    ignored:
      - response: 127.0.0.7
        description: "whitelisted"
      - response_range: 127.0.0.100-127.0.0.115
        description: "unexpected"
    blocked:
      - response: 127.255.255.254
        description: "blocked due to open resolver"
      - response_range: 127.0.0.120-127.0.0.135
    rate_limited:
      - response: 127.0.0.8
      - response_range: 127.255.255.0-127.255.255.254 # << collision with blocked open resolver
```
