### ISSUE TITLE
upload example dashboard (grafana)

### ISSUE THREAD

**Issue by till** [Luzilla/dnsbl_exporter#87]

**Comment by zentavr** [comment]
This is something I'm going to develop in a while

**Comment by stefangweichinger** [comment]
No dashboard(s) yet? How do you guys use this? Only set alerts in alertmanager? examples? thanks!

**Comment by zentavr** [comment]
@stefangweichinger i have something very basic. + Alertmanager, yes.

**Comment by till** [comment]
Same. But happy to take contributions. Will try to roll a new release this month as well.

**Comment by stefangweichinger** [comment]
great to hear. Could one of you share the alert definition? Or even add it to the README? ;-) thanks

**Comment by till** [comment]
> great to hear. Could one of you share the alert definition? Or even add it to the README? ;-) thanks
> 

It's just the usual:

```yaml
- alert: MxListed
  expr: readme query example
  for: 1m or your scrape interval
  labels:
    prio: page
  annotations:
    summary: ...
    description: ...
```

The readme has a query example already. Does that help? If you'd improve on it, I'd be happy to merge too. :)

**Comment by stefangweichinger** [comment]
> > great to hear. Could one of you share the alert definition? Or even add it to the README? ;-) thanks
> 
> It's just the usual:
> 
> ```yaml
> - alert: MxListed
>   expr: readme query example
>   for: 1m or your scrape interval
>   labels:
>     prio: page
>   annotations:
>     summary: ...
>     description: ...
> ```
> 
> The readme has a query example already. Does that help? If you'd improve on it, I'd be happy to merge too. :)

;-) I see. I'll try maybe.

**Comment by stefangweichinger** [comment]
Writing my alerts now ...

question: in the query, what is the IP?

```
cat dnsbl_exporter.yml 
groups:
  - name: dnsbl_exporter
    rules:
      - alert: MxListed
        expr: luzilla_rbls_ips_blacklisted{hostname="co.oops.co.at",ip="45.84.138.128",rbl="ix.dnsbl.manitu.net"}
        for: 1m
```

Do I have to list both FQDN and IP? Wouldn't it be able to query DNS for that? Or do I misunderstand? thanks.
