### ISSUE TITLE
upload sample alert (alertmanager)

### ISSUE THREAD

**Issue by till** [Luzilla/dnsbl_exporter#88]

**Comment by zentavr** [comment]
Do you seek for something like this:
```yaml
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: dnsbl-rules
    spec:
      groups:
        - name: dnsbl
          rules:
            - alert: RblsIpsBlacklisted
              expr: luzilla_rbls_ips_blacklisted > 0
              for: 15m
              labels:
                severity: critical
              annotations:
                description: '{{ $labels.hostname }} ({{ $labels.ip }}) has been blacklisted in {{ $labels.rbl }} for more than 15 minutes.'
                summary: 'Endpoint {{ $labels.hostname }} is blacklisted'
```
